/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#e5e2e1',
        'tertiary-container': '#c78f00',
        'system-amber': '#FFB800',
        'primary-fixed-dim': '#ffb693',
        'on-primary-container': '#572000',
        'surface-variant': '#353535',
        'background': '#131313',
        'surface': '#131313',
        'on-secondary-container': '#bab8b7',
        'on-tertiary': '#412d00',
        'on-tertiary-fixed-variant': '#5e4200',
        'primary-container': '#ff6b00',
        'on-secondary': '#313030',
        'primary-fixed': '#ffdbcc',
        'tertiary': '#ffba20',
        'on-primary': '#561f00',
        'surface-dim': '#131313',
        'terminal-black': '#050505',
        'status-safe': '#00E676',
        'outline': '#a98a7d',
        'tertiary-fixed-dim': '#ffba20',
        'surface-container-lowest': '#0e0e0e',
        'surface-bright': '#393939',
        'error-container': '#93000a',
        'on-secondary-fixed': '#1c1b1b',
        'on-tertiary-fixed': '#271900',
        'glass-border': 'rgba(255, 107, 0, 0.15)',
        'outline-variant': '#5a4136',
        'secondary': '#c9c6c5',
        'on-primary-fixed': '#351000',
        'inverse-on-surface': '#313030',
        'on-secondary-fixed-variant': '#474646',
        'surface-tint': '#ffb693',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#7a3000',
        'inverse-surface': '#e5e2e1',
        'on-error-container': '#ffdad6',
        'on-surface': '#e5e2e1',
        'surface-container-highest': '#353535',
        'surface-container-low': '#1c1b1b',
        'status-critical': '#FF3D00',
        'secondary-fixed': '#e5e2e1',
        'secondary-container': '#4a4949',
        'error': '#ffb4ab',
        'surface-container': '#20201f',
        'surface-container-high': '#2a2a2a',
        'on-surface-variant': '#e2bfb0',
        'on-tertiary-container': '#422d00',
        'primary': '#ffb693',
        'secondary-fixed-dim': '#c9c6c5',
        'tertiary-fixed': '#ffdea8',
        'inverse-primary': '#a04100',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '12px',
        'sidebar-width': '280px',
        unit: '4px',
        'margin-desktop': '24px',
        gutter: '16px',
        'console-height': '200px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-md': ['JetBrains Mono', 'monospace'],
        'code-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'code-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
